---
title: "Ejemplo ej 5, capitulo 3"
author: "Sonya Leilany Lorea Aguilera"
date: "2025-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r}
B<-1

f_den <- function(x, B=1){
  if (x>=-B & x<=0){
    y <- 1/B^2 *x +1/B
  } else if (x>0 & x<=B){
    y <- -1/B^2 *x +1/B
  }else{
    y <- 0
  }
  return(y)
}

fv_den <- Vectorize(f_den, "x")

f_dis <- function(x, B=1){
  if(x<(-1)*B){
    y<-0}else if (x>=-B & x<=0){
    y <- (X+B)*fv_den(x)/2
  }else if (x>0 & x<=B){
    y <- 1- (B-x)*fv_den(x)/2
  }else{
    y <- 0
  }
  return(y)
}

x<- seq(-1.5, 1.5, lenght.out=500)
y<-sapply(x, f_den)

ggplot()+
  #geom_line(aes(x,y), color="dodgerblue", linewidth=1.2)+
  geom_function(fun = fv_den, color="dodgerblue", linewidth=1.2)+
  xlim(-1.5, 1.5)+
  theme_bw()


```

```{r}
decision <- function(Vj, Vi, B=1){
  Vji <- Vj - Vi
  Pvj <- f_dis(Vji)
  
  ggplot()+
  geom_function(fun = fv_den, color="dodgerblue", linewidth=1.2, xlim=c(-B-0.1, B+0.1))+
    stat_function(fun=fv_den, geom= "area", fill="goldenrod3", alpha=0.5, xlim=c(-B, Vji)) +  geom_text(aes(B/2,1/(2*B), label=paste0("Prob(Vj)=", round(Pvj,2), sep="")))+labs(title="Probabilidad de elección")+
  theme_bw()
  
  
}


decision(Vj=6, Vi=5.5)
```

